// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6bBZvfEdvBTUp9ujaw_fU3jJLLj9w-Wo',
    appId: '1:494818832624:web:d97787d9ad61f925d51235',
    messagingSenderId: '494818832624',
    projectId: 'agrotech-f600a',
    authDomain: 'agrotech-f600a.firebaseapp.com',
    storageBucket: 'agrotech-f600a.appspot.com',
    measurementId: 'G-815GRT8SLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn_HUEmO_gvOnl_G8r2_PoHxJA9SpJ1PA',
    appId: '1:494818832624:android:68cb67b2144cb4afd51235',
    messagingSenderId: '494818832624',
    projectId: 'agrotech-f600a',
    storageBucket: 'agrotech-f600a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf7UrBJ9pvAFuztkdoJzOt_OAf8c2HnJ8',
    appId: '1:494818832624:ios:2c245106a9421861d51235',
    messagingSenderId: '494818832624',
    projectId: 'agrotech-f600a',
    storageBucket: 'agrotech-f600a.appspot.com',
    iosBundleId: 'com.example.agrotechMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf7UrBJ9pvAFuztkdoJzOt_OAf8c2HnJ8',
    appId: '1:494818832624:ios:2c245106a9421861d51235',
    messagingSenderId: '494818832624',
    projectId: 'agrotech-f600a',
    storageBucket: 'agrotech-f600a.appspot.com',
    iosBundleId: 'com.example.agrotechMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6bBZvfEdvBTUp9ujaw_fU3jJLLj9w-Wo',
    appId: '1:494818832624:web:91d48ab81a264cd7d51235',
    messagingSenderId: '494818832624',
    projectId: 'agrotech-f600a',
    authDomain: 'agrotech-f600a.firebaseapp.com',
    storageBucket: 'agrotech-f600a.appspot.com',
    measurementId: 'G-72WEKJF4NJ',
  );
}
